#!/bin/bash

ls /home/zbyerly/movies/data/cart/rho*.dat > filelist
par=0
while read datafile
do
cp $datafile /home/zbyerly/movies/input.dat
./single_frame.gpt
mv rho.png /home/zbyerly/movies/images/cart/rho$par.png
(( par++ ))
done < filelist

ffmpeg -qscale 1 -r 20 -b 9600 -i /home/zbyerly/movies/images/cart/rho%d.png cart.mp4

